"""Shared data models for the crypto trading system.

Key difference from stock system: quantities are float (fractional crypto amounts).
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from crypto.core.enums import (
    AlertSeverity,
    MarketRegime,
    OrderSide,
    OrderStatus,
    OrderType,
    PositionStatus,
    SignalStrength,
    Timeframe,
)


@dataclass
class Candle:
    """OHLCV price candle."""
    symbol: str
    timeframe: Timeframe
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float

    @property
    def mid(self) -> float:
        return (self.high + self.low) / 2

    @property
    def range(self) -> float:
        return self.high - self.low

    @property
    def body(self) -> float:
        return abs(self.close - self.open)

    @property
    def is_bullish(self) -> bool:
        return self.close >= self.open


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    strategy_id: str = ""
    symbol: str = ""
    side: OrderSide = OrderSide.BUY
    strength: SignalStrength = SignalStrength.MODERATE
    confidence: float = 0.0
    entry_price: float = 0.0
    stop_loss: float = 0.0
    target_price: float = 0.0
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: dict = field(default_factory=dict)

    @property
    def risk_reward_ratio(self) -> float:
        risk = abs(self.entry_price - self.stop_loss)
        if risk == 0:
            return 0.0
        reward = abs(self.target_price - self.entry_price)
        return reward / risk


@dataclass
class Order:
    """Order to be placed or already placed."""
    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    symbol: str = ""
    side: OrderSide = OrderSide.BUY
    order_type: OrderType = OrderType.MARKET
    quantity: float = 0.0  # Float for fractional crypto
    price: float = 0.0
    stop_price: float = 0.0
    target_price: float = 0.0
    status: OrderStatus = OrderStatus.PENDING
    strategy_id: str = ""
    signal_id: str = ""
    exchange_order_id: Optional[str] = None
    placed_at: Optional[datetime] = None
    filled_at: Optional[datetime] = None
    filled_price: float = 0.0
    filled_quantity: float = 0.0
    timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass
class Position:
    """An open or closed trading position."""
    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    symbol: str = ""
    side: OrderSide = OrderSide.BUY
    quantity: float = 0.0  # Float for fractional crypto
    entry_price: float = 0.0
    current_price: float = 0.0
    stop_loss: float = 0.0
    target_price: float = 0.0
    status: PositionStatus = PositionStatus.OPEN
    strategy_id: str = ""
    entry_order_id: str = ""
    exit_order_id: Optional[str] = None
    opened_at: datetime = field(default_factory=datetime.utcnow)
    closed_at: Optional[datetime] = None

    @property
    def unrealized_pnl(self) -> float:
        multiplier = 1 if self.side == OrderSide.BUY else -1
        return multiplier * (self.current_price - self.entry_price) * self.quantity

    @property
    def unrealized_pnl_pct(self) -> float:
        if self.entry_price == 0:
            return 0.0
        multiplier = 1 if self.side == OrderSide.BUY else -1
        return multiplier * (self.current_price - self.entry_price) / self.entry_price * 100

    @property
    def notional_value(self) -> float:
        return abs(self.current_price * self.quantity)


@dataclass
class Trade:
    """A completed trade with entry and exit details."""
    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    symbol: str = ""
    side: OrderSide = OrderSide.BUY
    quantity: float = 0.0
    entry_price: float = 0.0
    exit_price: float = 0.0
    strategy_id: str = ""
    entry_time: datetime = field(default_factory=datetime.utcnow)
    exit_time: Optional[datetime] = None
    commission: float = 0.0

    @property
    def pnl(self) -> float:
        multiplier = 1 if self.side == OrderSide.BUY else -1
        gross = multiplier * (self.exit_price - self.entry_price) * self.quantity
        return gross - self.commission

    @property
    def pnl_pct(self) -> float:
        if self.entry_price == 0:
            return 0.0
        multiplier = 1 if self.side == OrderSide.BUY else -1
        return multiplier * (self.exit_price - self.entry_price) / self.entry_price * 100

    @property
    def is_winner(self) -> bool:
        return self.pnl > 0


@dataclass
class PortfolioState:
    """Snapshot of the portfolio at a point in time."""
    total_capital: float = 0.0
    available_capital: float = 0.0
    positions: list[Position] = field(default_factory=list)
    rolling_pnl: float = 0.0  # Rolling 24h P&L (no daily reset for crypto)
    rolling_pnl_pct: float = 0.0
    total_exposure: float = 0.0
    max_drawdown: float = 0.0
    current_drawdown: float = 0.0
    peak_capital: float = 0.0
    timestamp: datetime = field(default_factory=datetime.utcnow)

    @property
    def open_position_count(self) -> int:
        return len([p for p in self.positions if p.status == PositionStatus.OPEN])

    @property
    def total_unrealized_pnl(self) -> float:
        return sum(p.unrealized_pnl for p in self.positions if p.status == PositionStatus.OPEN)


@dataclass
class StrategyPerformance:
    """Performance metrics for a single strategy."""
    strategy_id: str = ""
    total_trades: int = 0
    winning_trades: int = 0
    losing_trades: int = 0
    total_pnl: float = 0.0
    max_drawdown: float = 0.0
    current_drawdown: float = 0.0
    peak_pnl: float = 0.0
    is_enabled: bool = True

    @property
    def win_rate(self) -> float:
        if self.total_trades == 0:
            return 0.0
        return self.winning_trades / self.total_trades * 100

    @property
    def avg_pnl_per_trade(self) -> float:
        if self.total_trades == 0:
            return 0.0
        return self.total_pnl / self.total_trades


@dataclass
class Alert:
    """System alert or notification."""
    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    severity: AlertSeverity = AlertSeverity.INFO
    source: str = ""
    message: str = ""
    timestamp: datetime = field(default_factory=datetime.utcnow)
    acknowledged: bool = False
